services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:debug reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
    # volumes:
    #   - /mnt/volumeE/study-folder/NestJS/ReservationMangement/reservation-mgmt/apps/reservations:/usr/src/app/apps/reservations
    #   - /mnt/volumeE/study-folder/NestJS/ReservationMangement/reservation-mgmt/apps/reservations/node_modules
    environment:
      - NODE_ENV=development

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
      - '3002:3002'
    volumes:
      - .:/usr/src/app
    # volumes:
    #   - /mnt/volumeE/study-folder/NestJS/ReservationMangement/reservation-mgmt/apps/auth:/usr/src/app/apps/auth
    #   - /mnt/volumeE/study-folder/NestJS/ReservationMangement/reservation-mgmt/apps/auth/node_modules
    environment:
      - NODE_ENV=development

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    ports:
      - '3003:3003'
      - '3004:3004'
    volumes:
      - .:/usr/src/app
    # volumes:
    #   - /mnt/volumeE/study-folder/NestJS/ReservationMangement/reservation-mgmt/apps/payments:/usr/src/app/apps/payments
    #   - /mnt/volumeE/study-folder/NestJS/ReservationMangement/reservation-mgmt/apps/payments/node_modules
    environment:
      - NODE_ENV=development

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
    # volumes:
    #   - /mnt/volumeE/study-folder/NestJS/ReservationMangement/reservation-mgmt/apps/payments:/usr/src/app/apps/payments
    #   - /mnt/volumeE/study-folder/NestJS/ReservationMangement/reservation-mgmt/apps/payments/node_modules
    environment:
      - NODE_ENV=development

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    volumes:
      - .:/usr/src/app
    ports:
      - '3006:3006'
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
