services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:debug reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
      - '3002:3002'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    ports:
      - '3003:3003'
      - '3004:3004'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development

  mysql:
    image: mysql
    ports:
      - '3306:3306'
    env_file:
      - .env
    # volumes:
    #   - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
