services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    # command: pnpm run start:dev reservations
    command: pnpm run start:debug:reservations reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    # command: pnpm run start:dev auth
    command: pnpm run start:debug:auth auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
      - '3002:3002'
      - '9230:9230'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    # command: pnpm run start:dev payments
    command: pnpm run start:debug:payments payments
    env_file:
      - ./apps/payments/.env
    ports:
      - '3003:3003'
      - '3004:3004'
      - '9231:9231'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    # command: pnpm run start:dev notifications
    command: pnpm run start:debug:notifications notifications
    env_file:
      - ./apps/notifications/.env
    ports:
      - '9232:9232'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
