apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  ports:
  - name: "tcp"
    port: 3005
    protocol: TCP
    targetPort: 3005
  selector:
    app: notifications
  type: ClusterIP
