services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image: asia-south1-docker.pkg.dev/reservationmanagment/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: asia-south1-docker.pkg.dev/reservationmanagment/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
      - '3002:3002'
  payments:
    image: asia-south1-docker.pkg.dev/reservationmanagment/payments/production
    ports:
      - '3003:3003'
      - '3004:3004'
    env_file:
      - ../apps/payments/.env
  notifications:
    image: asia-south1-docker.pkg.dev/reservationmanagment/notifications/production
    ports:
      - '3005:3005'
    env_file:
      - ../apps/notifications/.env
  mongo:
    image: mongo
