apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments
  name: payments-http
spec:
  ports:
  - name: "http"
    port: 3004
    protocol: TCP
    targetPort: 3004
  selector:
    app: payments
  type: NodePort
